services:
  - type: web
    name: wasl-server
    env: go
    buildCommand: go build -o app
    startCommand: ./app
    healthCheckPath: /.well-known/assetlinks.json
    envVars:
      - key: PORT
        value: 8080
      - key: ANDROID_PACKAGE_NAME
        value: com.mhmd.wasl
      - key: ANDROID_SHA256_FINGERPRINT
        value: FD:F7:95:1B:2E:25:BF:4C:19:6F:48:91:A1:04:8A:82:71:ED:08:62:30:E5:93:5B:E9:2D:09:9A:4E:48:62:AF
      - key: IOS_TEAM_ID
        sync: false # This will be set manually in Render dashboard
      - key: IOS_BUNDLE_ID
        value: com.mhmd.wasl
      - key: IOS_APP_STORE_ID
        sync: false # This will be set manually in Render dashboard
      - key: ANDROID_STORE_URL
        value: https://play.google.com/store/apps/details?id=com.mhmd.wasl
      - key: IOS_STORE_URL
        sync: false # This will be set manually in Render dashboard 